<?php
//000000086400a:3:{i:0;a:17:{s:10:"article_id";s:2:"20";s:6:"cat_id";s:1:"3";s:5:"title";s:12:"公司介绍";s:7:"content";s:3067:"&lt;p&gt;深圳搜豹网络有限公司（简称：搜豹）于2015年注册成立，是一家以专业研发电子商务软件为主营业务的集团化公司，集销售、市场、产品研发、技术支持、产品实施、售后服务等诸多职能于一体的专业企业管理软件及电子商务应用解决方案供应商。&lt;/p&gt;&lt;p&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;历年来，为客户提供高质量的服务是搜豹的宗旨。扎根深圳，拓宽经营领域，扩大经营规模，巩固生存基础，促进公司集团化发展的进程。服务全面覆盖华南、华东、华中、华北等区域。&lt;/p&gt;&lt;p&gt;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;经过团队不断努力以及前瞻性钻研，已开发出一站式打造直营、批发、代理代销、连锁加盟全网营销的 
“搜豹分销系统”，适合中型商家多站点、多城市、布局式实现独立商城销售渠道的“搜豹多用户商城系统”，适合中小电商快速开启无线网络零售店铺的“搜豹手
机商城和微信商城”，发挥运营系统集成的“易通ERP”，以及客户关系管理的“客户宝CRM”等。从而有效帮助客户建立一个标准化规范化的流程体系，快速
进入电子商务的盈利时代。&lt;/p&gt;&lt;p&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;同时，为企业提供整体电商平台的解决方案。包括搜豹全网分销解决方案、搜豹多渠道解决方案、O2O解决方案、
供应商B2B2C解决方案、搜豹手机商城解决方案、搜豹微信商城解决方案、全网整合营销解决方案、行业解决方案。涉足各个行业，包括服装、IT、通讯、医
药、电子产品、家具、珠宝、建材等，在此构建一个多方共赢的商户生态系统。&lt;/p&gt;&lt;p&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;经过跨越式发展，让搜豹更了解市场，更贴近客户需求，“一切为了网商”的中心思想，“客户至尊至上，服务至善
至优”的经营理念使其迅速发展壮大，并始终走在行业的前列。搜豹集聚了国内电子商务及软件研发方面的人才、资产、管理和技术等优势资源，夯实了资源整合和
团队建设两个基础，突出了自主化创新和规模化发展，促进行业量化升级，调整优化公司内部结构，企业经济总量和经济规模跃上新台阶，为助推地方经济发展发挥
了积极作用。&lt;/p&gt;&lt;p&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;展望未来，搜豹不断创新，不断深挖行业动向，积极吸收先进的国内外思想与技术，逐步实现“搜豹平台
化+ERP+CRM+移动APP端+智能应用”的发展战略，成为行业信息化发展的管理源泉，为行业的深入发展应用创造不竭动力！触动灵感，共创未来，搜豹
与您携手共赢美好明天。&lt;/p&gt;&lt;p&gt;&lt;br/&gt;&lt;/p&gt;";s:6:"author";s:0:"";s:12:"author_email";s:0:"";s:8:"keywords";s:0:"";s:12:"article_type";s:1:"2";s:7:"is_open";s:1:"1";s:8:"add_time";s:1:"0";s:8:"file_url";s:0:"";s:9:"open_type";s:1:"0";s:4:"link";s:0:"";s:11:"description";N;s:5:"click";s:1:"1";s:12:"publish_time";s:1:"0";s:5:"thumb";s:0:"";}i:1;a:17:{s:10:"article_id";s:2:"21";s:6:"cat_id";s:1:"3";s:5:"title";s:12:"商城简介";s:7:"content";s:902:"&lt;p class=&quot;common_tit&quot;&gt;TPshop -- ( Thinkphp shop的简称 ) B2C 商城免费开源&lt;/p&gt;&lt;p&gt;TPshop 是用thinkphp开发的shop 一款免费开源网店系统，适合企业及个人,包含 (微信商城 + wap + android + ios + pc) 二次开发非常方便,
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; 详细的TPshop使用手册 + TPshop二开手册 + TPshop 98小时的二开视频教程，使开发者得心应手, 一看就懂 一听就会, 代码清晰简洁,通俗易懂. 丰富的插件和多套模板支持, 易扩展.
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;是目前国内首家最为完善的开源商城系统。系统支持多语言版本，操作简单,安全稳定,是广大用户二次开发的最佳选择。（需获取正规商业授权，方可做商业运营使用）&lt;/p&gt;&lt;p&gt;&lt;br/&gt;&lt;/p&gt;";s:6:"author";s:0:"";s:12:"author_email";s:0:"";s:8:"keywords";s:0:"";s:12:"article_type";s:1:"2";s:7:"is_open";s:1:"1";s:8:"add_time";s:1:"0";s:8:"file_url";s:0:"";s:9:"open_type";s:1:"0";s:4:"link";s:0:"";s:11:"description";N;s:5:"click";s:1:"1";s:12:"publish_time";s:1:"0";s:5:"thumb";s:0:"";}i:2;a:17:{s:10:"article_id";s:2:"22";s:6:"cat_id";s:1:"3";s:5:"title";s:12:"联系客服";s:7:"content";s:620:"&lt;p&gt;24小时 客服热线: 0755-86140485

有什么问题可以在线联系客服，&lt;/p&gt;&lt;p&gt;第一时间得到帮助.		 &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;br/&gt;&lt;/p&gt;&lt;p&gt;&amp;nbsp;				 &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;nbsp; &lt;br/&gt;&lt;/p&gt;&lt;p&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://wpa.qq.com/msgrd?v=3&amp;amp;uin=&amp;amp;site=qq&amp;amp;menu=yes&quot;&gt;&lt;img src=&quot;http://pub.idqqimg.com/wpa/images/counseling_style_53.png&quot; alt=&quot;有问题联系客服&quot; title=&quot;有问题联系客服&quot; border=&quot;0&quot;/&gt;&lt;/a&gt;&lt;/p&gt;";s:6:"author";s:0:"";s:12:"author_email";s:0:"";s:8:"keywords";s:0:"";s:12:"article_type";s:1:"2";s:7:"is_open";s:1:"1";s:8:"add_time";s:1:"0";s:8:"file_url";s:0:"";s:9:"open_type";s:1:"0";s:4:"link";s:0:"";s:11:"description";N;s:5:"click";s:1:"1";s:12:"publish_time";s:1:"0";s:5:"thumb";s:0:"";}}
?>